services:
  app:
    container_name: abantether
    image: abantether:latest
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"  # to load swagger static files
#      && gunicorn --workers=3 --timeout=600 --bind=0.0.0.0:8000 config.wsgi:application"

    depends_on:
      - postgres
      - redis
    env_file:
      - .compose/config.env
    networks:
      - abantether
    ports:
      - "8000:8000"
    restart: always

  postgres:
    container_name: abantether_postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abantether
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - abantether
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: abantether_redis
    image: redis:7.2
    networks:
      - abantether
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

networks:
  abantether:

volumes:
  postgres-data:
  redis-data: